services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - odoo-db:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  odoo:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: odoo
      DB_PASSWORD: odoo
      DB_NAME: odoo
    ports:
      - "8069:8069"
    volumes:
      - odoo-data:/var/lib/odoo
    restart: unless-stopped

volumes:
  odoo-db:
  odoo-data:
